# Generated by Django 5.2.8 on 2026-02-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='4dce0a52923', max_length=11, unique=True),
        ),
    ]
