# Generated by Django 6.0 on 2025-12-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='b54727f7551', max_length=11, unique=True),
        ),
    ]
