# Generated by Django 5.2.8 on 2026-02-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
    ]
