# Generated by Django 5.2.8 on 2026-02-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_remove_sku_field_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='dee829ccb20', max_length=11, unique=True),
        ),
    ]
