# Generated by Django 5.2.8 on 2026-02-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_remove_sku_column'),
        ('apiApp', '0003_remove_sku_field_final'),
    ]

    operations = [
    ]
