# Generated by Django 6.0 on 2025-12-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='177c698dde9', max_length=11, unique=True),
        ),
    ]
