# Generated by Django 5.2.8 on 2026-02-05 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_alter_cart_cart_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='A description of the image for accessibility', max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='77ba6326806', max_length=11, unique=True),
        ),
    ]
