# Generated by Django 6.0 on 2025-12-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_customuser_user_type_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='418a947b153', max_length=11, unique=True),
        ),
    ]
