# Generated by Django 5.2.8 on 2026-02-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_remove_productimage_image_url_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating_field',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='9b2a1b842ce', max_length=11, unique=True),
        ),
    ]
