# Generated by Django 5.2.8 on 2026-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_rename_rating_field_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='a7b975f396f', max_length=11, unique=True),
        ),
    ]
