# Generated by Django 6.0 on 2026-01-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='875c6faadf8', max_length=11, unique=True),
        ),
    ]
