# Generated by Django 6.0 on 2026-01-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0008_customuser_full_name_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='6a425cf527d', max_length=11, unique=True),
        ),
    ]
