# Generated by Django 6.0 on 2026-01-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='c17260ab942', max_length=11, unique=True),
        ),
    ]
