# Generated by Django 5.2.8 on 2026-02-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0010_alter_cart_cart_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='4a03a709508', max_length=11, unique=True),
        ),
    ]
