# Generated by Django 5.2.8 on 2026-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_remove_category_image_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='6584753c235', max_length=11, unique=True),
        ),
    ]
