# Generated by Django 6.0 on 2026-01-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0012_cart_user_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='ec184958f59', max_length=11, unique=True),
        ),
    ]
