# Generated by Django 5.2.8 on 2026-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0013_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='1ef9075467f', max_length=11, unique=True),
        ),
    ]
