# Generated by Django 5.2.8 on 2026-01-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0014_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='b112556b265', max_length=11, unique=True),
        ),
    ]
