# Generated by Django 5.2.8 on 2026-01-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0016_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='d5917e7a0ba', max_length=11, unique=True),
        ),
    ]
