# Generated by Django 5.2.8 on 2026-01-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0019_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='8e9a95f92e1', max_length=11, unique=True),
        ),
    ]
