# Generated by Django 5.2.8 on 2026-01-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0022_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='b15c2b8a1e4', max_length=11, unique=True),
        ),
    ]
