# Generated by Django 5.2.8 on 2026-01-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0023_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='fd0be2cb3d5', max_length=11, unique=True),
        ),
    ]
