# Generated by Django 5.2.8 on 2026-01-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0024_alter_cart_cart_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='544b395abef', max_length=11, unique=True),
        ),
    ]
