# Generated by Django 5.2.8 on 2026-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0025_remove_customuser_username_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='9ad3d77f72a', max_length=11, unique=True),
        ),
    ]
