# Generated by Django 5.2.8 on 2026-02-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0029_customeraddress_alt_phone_customeraddress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='3200ef499ba', max_length=11, unique=True),
        ),
    ]
