# Generated by Django 5.2.8 on 2026-02-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0034_rename_user_type_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='bf14669a1f5', max_length=11, unique=True),
        ),
    ]
