# Generated by Django 5.2.8 on 2026-02-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0036_remove_customuser_role_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='deeceea210c', max_length=11, unique=True),
        ),
    ]
