# Generated by Django 5.2.8 on 2026-02-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0037_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='bc71b581ef5', max_length=11, unique=True),
        ),
    ]
