# Generated by Django 5.2.8 on 2026-02-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0039_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='2ef18a919ca', max_length=11, unique=True),
        ),
    ]
