# Generated by Django 5.2.8 on 2026-02-03 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0041_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='helpcenterarticle',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='alt_phone',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='helpcenterarticle',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='helpcenterarticle',
            name='order',
        ),
        migrations.RemoveField(
            model_name='helpcenterarticle',
            name='published',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_sent_at',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpcenterarticle',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(default='70ad8bd0126', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='helpcenterarticle',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('orders', 'Orders'), ('payments', 'Payments'), ('shipping', 'Shipping'), ('returns', 'Returns'), ('account', 'Account')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='helpcenterarticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='helpcenterarticle',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmailNotificationPreference',
        ),
    ]
